# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Main Service Connection'
    subscriptionId: '7ae2712e-1398-44cf-9a64-49071835b5e9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'certificate-rotation-demo'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'https://raw.githubusercontent.com/lloydtawanda/azure-certificate-rotation/main/certificate-rotation.json'
    csmParametersFile: 'https://raw.githubusercontent.com/lloydtawanda/azure-certificate-rotation/main/certificate-rotation.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'ARMDeploymentPipeline'
